export const agendaTypes = {
  CREATE: "CREATE_AGENDA",
  GET_SINGLE: "GET_SINGLE_AGENDA",
  DELETE: "DELETE_AGENDA",
  LOGOUT: "LOGOUT"
}

export const contactTypes = {
  CREATE: "CREATE_CONTACT",
  GET: "GET_CONTACTS",
  UPDATE: "UPDATE_CONTACT",
  DELETE: "DELETE_CONTACTS",
  DELETE_SINGLE: "DELETE_SINGLE_CONTACT"
}